const dares = [
  "Dance for 10 seconds without music.",
  "Speak in a robot voice for 1 minute.",
  "Do your best celebrity impression.",
  "Say the alphabet backwards as far as you can.",
  "Make a funny face and hold it for 10 seconds.",
  "Talk without using the word 'I' for 1 minute.",
  "Send a random emoji to your best friend.",
  "Pretend you are a news reporter for 30 seconds.",
  "Laugh like a villain for 10 seconds.",
  "Compliment someone near you.",
  "Act like a cat for 20 seconds.",
  "Tell a joke, even if it is bad.",
  "Walk like a model for 10 seconds.",
  "Say 'I am Batman' dramatically.",
  "Invent a new dance move right now.",

  "Sing the chorus of your favorite song.",
  "Do 5 jumping jacks.",
  "Talk in a British accent for 1 minute.",
  "Pretend you are taking a serious interview.",
  "Say one nice thing about yourself.",
  "Make a dramatic movie trailer about your life.",
  "Try not to laugh for 30 seconds.",
  "Tell everyone your most used emoji.",
  "Do your best animal sound.",
  "Pretend your phone is a microphone and give a speech.",
  "Say a tongue twister 3 times fast.",
  "Make up a superhero name for yourself.",
  "Speak only in whispers for 1 minute.",
  "Draw a smiley face in the air with your finger.",
  "Act like you just won an award.",
  "Say 'I am the boss' in your most serious voice.",
  "Pretend to be a fitness trainer for 30 seconds.",
  "Give a motivational speech to the room.",
  "Make a fake advertisement for a water bottle.",
  "Do your best slow-motion walk.",
  "Say something funny without smiling.",
  "Pretend you are a chef explaining Maggi like a luxury dish.",
  "Name 5 things that are pink.",
  "Balance something safe on your head for 10 seconds.",
  "Talk like a cartoon character.",
  "Pretend you are a cricket commentator.",
  "Make a weird sound and ask others to copy it.",
  "Do an imaginary ramp walk.",
  "Say your name like a movie villain.",
  "Create a new greeting and teach it to everyone.",
  "Pretend you are stuck in an elevator and need help.",
  "Do your best baby voice.",
  "Say 'Made by Priyanka Verma' like a superstar announcement.",
  "Pretend you are ordering food in a royal palace.",
  "Act like a teacher for 30 seconds.",
  "Make up a funny excuse for being late.",
  "Do a 10-second happy dance.",
  "Pretend your chair is a racing car.",
  "Say one random fact confidently.",
  "Give yourself a funny nickname.",
  "Pretend you are a YouTuber introducing your channel.",
  "Make a serious face while saying something silly.",
  "Describe your day using only movie names.",
  "Try to touch your nose with your tongue.",
  "Pretend you are calling customer care.",
  "Say 'Give Me a Dare' in 3 different styles.",
  "Act like you are walking on the moon.",
  "Tell a fake breaking news story.",
  "Do your best superhero pose.",
  "Pretend you are a magician and perform a fake trick.",
  "Say the months of the year backwards.",
  "Make up a funny product and sell it in 20 seconds.",
  "Pretend you are a news anchor reporting about pizza.",
  "Say one line in the most dramatic way possible.",
  "Act like a robot with low battery.",
  "Pretend you are a detective solving a missing cookie case.",
  "Make a funny sound every time someone says your name for 1 minute.",
  "Speak like an old wise person for 30 seconds.",
  "Pretend you are giving an Oscar speech.",
  "Do your best fake laugh.",
  "Create a funny handshake with someone.",
  "Say your favorite food like it is a secret password.",
  "Pretend to be a statue for 15 seconds.",
  "Describe yourself in 3 funny words.",
  "Say 'I am unstoppable' with full confidence.",
  "Pretend you are a tour guide for your room.",
  "Act like you are in a shampoo advertisement.",
  "Give a dramatic reaction to drinking water.",
  "Pretend you are selling invisible shoes.",
  "Talk like a pirate for 30 seconds.",
  "Say something nice about the person on your right.",
  "Invent a funny rule everyone must follow for 1 minute.",
  "Pretend you are a famous singer entering a concert.",
  "Make a silly face and take a selfie.",
  "Say one line as if you are in a horror movie.",
  "Act like your hand is a phone and answer a fake call.",
  "Pretend you are a DJ at a party.",
  "Name 3 things you would take to Mars.",
  "Say 'Dare completed!' like a game character.",
  "Create a fake app idea in 20 seconds.",
  "Pretend you are explaining Instagram to an alien.",
  "Do your best victory celebration.",
  "Talk like a weather reporter.",
  "Act like you are seeing snow for the first time.",
  "Say your favorite dialogue dramatically.",
  "Pretend your pen is a magic wand.",
  "Laugh without opening your mouth.",
  "Pretend you are a royal king or queen for 30 seconds.",
  "Make up a funny poem with 2 lines.",
  "Say 'Priyanka Verma built this app' like a movie trailer voice."
];

function generateDare() {
  const randomIndex = Math.floor(Math.random() * dares.length);
  const selectedDare = dares[randomIndex];

  document.getElementById("dareBox").innerText = selectedDare;
}